services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL="http://192.168.0.221:8082"

  backend:
    build: ./backend
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/tests/projects:/projects
    environment:
      - PORT=8080
      - PROJECT_DIR=/projects
